function out1 = dCOM(dq1,dq2,dq3,dq4,dq5,l1,l2,l4,lc1,lc2,lc3,lc4,lc5,m1,m2,m3,m4,m5,q1,q2,q3,q4,q5)
%DCOM
%    OUT1 = DCOM(DQ1,DQ2,DQ3,DQ4,DQ5,L1,L2,L4,LC1,LC2,LC3,LC4,LC5,M1,M2,M3,M4,M5,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-May-2020 15:18:25

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = sin(t3);
t5 = dq1.*l1.*t4;
t6 = q2+t2;
t7 = sin(t6);
t8 = dq2.*l2.*t7;
t9 = q4+t2;
t10 = sin(t9);
t11 = cos(t3);
t12 = dq1.*l1.*t11;
t13 = cos(t6);
t14 = q3+t2;
t15 = dq2.*l2.*t13;
t16 = cos(t9);
t17 = q5+t2;
t18 = m1+m2+m3+m4+m5;
t19 = 1.0./t18;
out1 = [-t19.*(m3.*(t5+t8+dq3.*lc3.*sin(t14))+m2.*(t5+dq2.*lc2.*t7)+m4.*(t5+t8-dq4.*lc4.*t10)+m5.*(t5+t8-dq5.*lc5.*sin(t17)-dq4.*l4.*t10)+dq1.*lc1.*m1.*t4);t19.*(m3.*(t12+t15+dq3.*lc3.*cos(t14))+m2.*(t12+dq2.*lc2.*t13)+m4.*(t12+t15-dq4.*lc4.*t16)+m5.*(t12+t15-dq5.*lc5.*cos(t17)-dq4.*l4.*t16)+dq1.*lc1.*m1.*t11)];
